spring.application.name=api-gateway
server.port=${PORT:8080}

# Trip Service
spring.cloud.gateway.routes[0].id=trip-service
spring.cloud.gateway.routes[0].uri=http://trip_service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/trips/**,/api/upload/**,/uploads/**,/api/notifications/**,/api/users/**

# Discover Service
spring.cloud.gateway.routes[1].id=discover-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/discover/**,/api/search/**,/api/profile/**,/api/follow/**,/api/plans/**